### ISSUE TITLE
App is stuck after login.

### ISSUE THREAD

**Issue by ZeeshanShabbir** [jurkian/react-bank#1]
I have clone cloned the app and using it with my own firebase configurations. I also have added a new user into firebase auth and enabled firestore as well but when i tried to login and app gets stuck and keep loading to /panel. 

Can you please point out what am i missing? I think there must be something in firestore missing. If you can share the schema of firestore as well

**Comment by mela1989** [comment]
I have the same issue, the login is stuck

**Comment by jurkian** [comment]
Sorry for no response guys, I left this app for a while due to lack of time.
I have now made a bigger update and it works again.

I've added API in Node and MongoDB, so everything is going to be local and easier to set up.
