### ISSUE TITLE
Running localhost:3001 on api folder

### ISSUE THREAD

**Issue by giantthinker** [jurkian/react-bank#3]
I get this output:
{"message":"Auth token not available or incorrect"}

**Comment by jurkian** [comment]
There are some publicly available API routes and there are secured ones which require valid token. You get token after logging in.

How can I reproduce this? Let me know when did this appear?

**Comment by giantthinker** [comment]
@jurkian on app initialisation. 
Especially the app keeps loading and showing refresh if it takes too long to load.

**Comment by jurkian** [comment]
I can't reproduce it... it all works fine, all the time.

Try to remove the token from localStorage (if you have one) and make sure you have all the files up to date (I've been fixing some bugs recently). Then start the app again.

Let me know if it helps.
